### ISSUE TITLE
垢画像null

### ISSUE THREAD

**Issue by KawakawaRitsuki** [KawakawaRitsuki/Twiback#14]
```
  64 TypeError: /Twiback/views/pages/dashboard.ejs:16↲
  65   ¦ 14|         <h2>Profile</h2>↲
  66   ¦ 15|         <br>↲
  67  >> 16|         <img class="icon" src="<%= user.profile_image_url_https.replace("_normal","") %>"></img>↲
  68   ¦ 17|         <div class="name"><%= user.name %></div>↲
  69   ¦ 18|         <div class="screen_name">@<%= user.screen_name %></div>↲
  70   ¦ 19|         <h2>Friends</h2>↲
  71 ↲
  72 Cannot read property 'profile_image_url_https' of null↲
  73   ¦ at eval (eval at compile (/Twiback/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:70:31)↲
  74   ¦ at returnedFn (/Twiback/node_modules/ejs/lib/ejs.js:653:17)↲
  75   ¦ at tryHandleCache (/Twiback/node_modules/ejs/lib/ejs.js:251:36)↲
  76   ¦ at View.exports.renderFile [as engine] (/Twiback/node_modules/ejs/lib/ejs.js:482:10)↲
  77   ¦ at View.render (/Twiback/node_modules/express/lib/view.js:135:8)↲
  78   ¦ at tryRender (/Twiback/node_modules/express/lib/application.js:640:10)↲
  79   ¦ at Function.render (/Twiback/node_modules/express/lib/application.js:592:3)↲
  80   ¦ at ServerResponse.render (/Twiback/node_modules/express/lib/response.js:1008:7)↲
  81   ¦ at app.get (/Twiback/index.js:110:7)↲
```

めっちゃこれある

**Comment by KawakawaRitsuki** [comment]
多分tokenが切れてる
tokenチェック処理挟むように
