### ISSUE TITLE
callbackが別の内容？

### ISSUE THREAD

**Issue by KawakawaRitsuki** [KawakawaRitsuki/Twiback#15]
```
  86 (node:1) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function↲
  87   ¦ at setTimeout (timers.js:379:11)↲
  88   ¦ at Promise (/Twiback/index.js:355:9)↲
  89   ¦ at new Promise (<anonymous>)↲
  90   ¦ at promises.push (/Twiback/index.js:353:25)↲
  91   ¦ at process._tickCallback (internal/process/next_tick.js:68:7)↲
```

**Comment by KawakawaRitsuki** [comment]
廃止
