### ISSUE TITLE
なんやこれ...

### ISSUE THREAD

**Issue by KawakawaRitsuki** [KawakawaRitsuki/Twiback#16]
```
 111 Node.js is listening to PORT:80↲
 112 /Twiback/node_modules/mongoose/node_modules/mongodb/lib/utils.js:132↲
 113   ¦ ¦ throw err;↲
 114   ¦ ¦ ^↲
 115 ↲
 116 TypeError: Cannot read property 'forEach' of undefined↲
 117   ¦ at User.find (/Twiback/index.js:56:11)↲
 118   ¦ at /Twiback/node_modules/mongoose/lib/model.js:4236:16↲
 119   ¦ at cb (/Twiback/node_modules/mongoose/lib/query.js:1365:14)↲
 120   ¦ at err (/Twiback/node_modules/mongoose/node_modules/mongodb/lib/utils.js:415:14)↲
 121   ¦ at executeCallback (/Twiback/node_modules/mongoose/node_modules/mongodb/lib/utils.js:404:25)↲
 122   ¦ at handleCallback (/Twiback/node_modules/mongoose/node_modules/mongodb/lib/utils.js:128:55)↲
 123   ¦ at self._endSession.self._endSession (/Twiback/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:900:36)↲
 124   ¦ at ClientSession.endSession (/Twiback/node_modules/mongoose/node_modules/mongodb-core/lib/sessions.js:72:41)↲
 125   ¦ at Cursor._endSession (/Twiback/node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:185:13)↲
 126   ¦ at Cursor._endSession (/Twiback/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:217:59)↲
 127   ¦ at /Twiback/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:900:18↲
 128   ¦ at handleCallback (/Twiback/node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:199:5)↲
 129   ¦ at /Twiback/node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:712:23↲
 130   ¦ at queryCallback (/Twiback/node_modules/mongoose/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:216:21)↲
 131   ¦ at /Twiback/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:544:18↲
 132   ¦ at process._tickCallback (internal/process/next_tick.js:61:11)↲
 133 Emitted 'error' event at:↲
 134   ¦ at /Twiback/node_modules/mongoose/lib/model.js:4238:13↲
 135   ¦ at cb (/Twiback/node_modules/mongoose/lib/query.js:1365:14)↲
 136   ¦ [... lines matching original stack trace ...]↲
 137   ¦ at process._tickCallback (internal/process/next_tick.js:61:11)↲
 138 Node.js is listening to PORT:80↲
 139 /Twiback/node_modules/mongoose/node_modules/mongodb/lib/utils.js:132↲
 140   ¦ ¦ throw err;↲
 141   ¦ ¦ ^↲
 142 ↲
```

**Comment by KawakawaRitsuki** [comment]
エラー処理してないのが悪そう
