### ISSUE TITLE
なにこれ2

### ISSUE THREAD

**Issue by KawakawaRitsuki** [KawakawaRitsuki/Twiback#17]
```
 344 (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'user' of undefined
 345   ¦ at Socket.socket.on (/Twiback/index.js:100:123)
 346   ¦ at Socket.emit (events.js:182:13)
 347   ¦ at /Twiback/node_modules/socket.io/lib/socket.js:528:12
 348   ¦ at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by KawakawaRitsuki** [comment]
sessionが破棄された状態でdashboardを開くとこれが出る
